services:
  stockinho:
    tty: true
    stdin_open: true
    image: node:20.18.0
    container_name: stockinho
    working_dir: /app
    command: make quero-boot-startup-worker
    ports:
      - 3400:3400
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./stockinho:/app:cached
      - ./stockinho/stockinho-node-modules:/app/node_modules

  kafka:
    container_name: kafka
    image: querodevops/kafka-kafkacat:2.0
    ports:
      - 9092:9092
    env_file:
      - envs/kafka.env
    depends_on:
      - zookeeper
    volumes:
      - ./configs/kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  kafsender:
    tty: true
    stdin_open: true
    build:
      context: ./kafsender
    working_dir: /kafsender
    command: make start-web
    ports:
      - 9500:9500
    env_file:
      - envs/kafsender.env
    depends_on:
      - kafsender-api
      - kafka
    volumes:
      - ./kafsender:/kafsender

  kafsender-api:
    tty: true
    stdin_open: true
    build:
      context: ./kafsender
    working_dir: /kafsender
    command: make start-api
    ports:
      - 9501:9501
    env_file:
      - envs/kafsender.env
    depends_on:
      - kafka
    volumes:
      - ./kafsender:/kafsender

  mini-indexer:
    container_name: mini-indexer
    build:
      context: ./mini-indexer
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./mini-indexer:/usr/src/app:rw
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - elasticsearch
      - kibana

  postgres:
    container_name: postgres
    image: 'postgres:13.6-alpine'
    environment:
      - POSTGRES_DB=mini_indexer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
    env_file:
      - envs/zookeeper.env
    volumes:
      - ./configs/zookeeper/zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf

volumes:
  postgres:
