services:
  stockinho:
    tty: true
    stdin_open: true
    image: node:20.18.0
    container_name: stockinho
    working_dir: /app
    command: make stockinho
    ports:
      - 3400:3400
    depends_on:
      - postgres13
      - kafka
      - kafsender
    volumes:
      - ./stockinho:/app:cached
      - stockinho-node-modules:/app/node_modules
  kafsender:
    container_name: kafksender
    ports:
      - 9501:9501
    image: node:18.15
    build:
      context: ./kafsender
      dockerfile: Dockerfile

  mini-indexer:
    container_name: mini-indexer
    build:
      context: ./mini-indexer
      dockerfile: Dockerfile 
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./mini-indexer:/usr/src/app:rw
    ports:
      - 3000:3000
    depends_on:
      - mini-indexer-postgres
      - elasticsearch
      - kibana

  mini-indexer-postgres:
    container_name: mini-indexer-postgres
    image: 'postgres:13.6-alpine'
    environment:
      - POSTGRES_DB=mini_indexer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  postgres:
